name: nthack
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^23.2.4
  csv: ^5.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/year_csvs/
      - assets/quarter_csvs/
      - assets/month_csvs/
  
  fonts: 
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Light.ttf
          - asset: assets/fonts/OpenSans-Medium.ttf